services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cidadesinteligentes_app
    container_name: cidadesinteligentes_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - cidadesinteligentes-network
    volumes:
      - .:/app

networks:
  cidadesinteligentes-network:
    driver: bridge
