name: Continuous Delivery

on:
  push:
    branches: "main"
 
env:
  IMAGE_NAME: smartcity-fiap
  AZURE_WEBAPP_NAME: smartcity-fiap
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout 
        uses: actions/checkout@v4 

      - name: Setup Java SDK 
        uses: actions/setup-java@v4 
        with: 
          distribution: 'temurin'  
          java-version: '21'

      # Adicionando passo para construir o projeto com Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Listar arquivos de saída para verificar se o JAR foi gerado corretamente
      - name: List build/libs directory
        run: ls -l build/libs

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
